url: "https://tmgindex.netlify.app"
baseurl: ""
title: "the Mountain Goats Index"

collections:
  shows:
    output: true
  records:
    output: true
  songs:
    output: true


defaults:
  - scope:
      path: ""
      type: "shows"
    values:
      layout: "show"
      permalink: /:collection/:year-:month-:day-:title/
  - scope:
      path: ""
      type: "records"
    values:
      layout: "record"  
      permalink: /:collection/:title/
  - scope:
      path: ""
      type: "songs"
    values:
      layout: "song"
      permalink: /:collection/:title/
  

plugins:
  - jekyll-datapage-generator

page_gen-dirs: true

page_gen:
  - data: songs
    template: song
    name: title
    index_files: true